---
- hosts: localhost

  tasks:

    - name: Stop and remove webserver container
      docker_container:
        name: webserver
        state: absent

    - name: Stop and remove webclient container
      docker_container:
        name: webclient
        state: absent

    - name: Stop and remove mongo container
      docker_container:
        name: database
        state: absent

    - name: Remove webserver image
      docker_image:
        name: mod6_server
        tag: 459
        state: absent

    - name: Remove mongo image
      docker_image:
        name: mod6_database
        tag: 459
        state: absent

    - name: Remove webclient image 
      docker_image:
        name: mod6_webclient
        tag: 459
        state: absent

    - name: Remove data container
      docker_volume:
        name: mongo_data
        state: absent

    - name: Remove config container
      docker_volume:
        name: mongo_config
        state: absent
