---
- hosts: localhost

  tasks:

    - name: Build webserver image
      docker_image:
        name: mod6_server
        tag: 459
        path: ./server

    - name: Build mongo image
      docker_image:
        name: mod6_database
        tag: 459
        path: ./mongo

    - name: Build business logic image
      docker_image:
        name: mod6_webclient
        tag: 459
        path: ./webclient

    - name: Create docker volume for the database
      docker_volume:
        name: mongo_data
      register: created_volume

    - name: Create docker volume for the database configuration
      docker_volume:
        name: mongo_config

    - name: Start mongo database container
      docker_container:
        name: database
        image: mod6_database:459
        volumes:
          - mongo_data:/data/db
          - mongo_config:/data/configdb

    - name: Wait for the database to start up
      wait_for:
        timeout: 10
      when: created_volume.changed

    - name: Create student collection
      shell: docker exec -i database mongo < mongo/CreateObjects.mongo
      when: created_volume.changed

    - name: Add sample data
      shell: docker exec -i database mongo < mongo/AddStudents.mongo
      when: created_volume.changed

    -  name: Start business logic container
       docker_container:
         name: webclient
         image: mod6_webclient:459
         published_ports:
           - 8080:5000
         env:
           ZMQ_REQ_PORT: 3000

    - name: Start python webserver container
      docker_container:
        name: webserver
        image: mod6_server:459
        expose:
          - "3000"
        env:
          ZMQ_BIND_PORT: 3000
